'\" t
.\"     Title: tlsrpt-fetcher
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-10-31
.\"    Manual: tlsrpt-fetcher
.\"    Source: tlsrpt-fetcher
.\"  Language: English
.\"
.TH "TLSRPT\-FETCHER" "1" "2024-10-31" "tlsrpt\-fetcher" "tlsrpt\-fetcher"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt\-fetcher \- The data transfer agent to bring TLSRPT report data from the tlsrpt\-receiver to the tlsrpt\-reporter.
.SH "SYNOPSIS"
.sp
\fBtlsrpt\-fetcher\fP [\fIOPTION\fP] \fIDAY\fP [\fIDOMAIN\fP]
.SH "DESCRIPTION"
.sp
The tlsrpt\-fetcher is called by the tlsrpt\-reporter to collect the pre\-aggregated data from tlsrpt\-receivers.
The data retrieval is done in two steps.
.sp
In the first step, the reporter asks for a list of domains for which data was collected.
.sp
In this step the reporter first checks if the tlsrpt\-fetcher supports a matching protocol version in case future versions will use a different protocol.
The fetcher\-protocol version is therefore the first line.
.sp
The second line is the current time of the tlsrpt\-receiver/tlsrpt\-fetcher bundle.
If the time differs too much from the time of the tlsrpt\-reporter a warning is given that the data may not be completely processed.
.sp
The following lines are the domains, one domain per line.
The end of the list is signalled by a line containing just one single "."
.SH "OPTIONS"
.sp
\fB\-\-storage\fP=\fIURL\fP
.RS 4
Use data storage described by \fIURL\fP.
.RE
.SS "General options"
.sp
\fB\-\-config_file\fP=\fIfilename\fP
.RS 4
Read options from the section tlsrpt_fetcher of the INI\-style configuration file \fIfilename\fP.
Environment variables override setings from the configurstion file and command line options override both.
.RE
.sp
\fB\-\-help\fP
.RS 4
Print a help message describing all options.
.RE
.SS "Logging options"
.sp
\fB\-\-logfilename\fP=\fIfilename\fP
.RS 4
Use \fIfilename\fP as log file.
.RE
.sp
\fB\-\-log_level\fP=\fIlevel\fP
.RS 4
Set log level to \fIlevel\fP, allowed values: debug, info, warn, error.
.RE
.SH "ENVIRONMENT"
.sp
All config options except \-\-help and \-\-config_file can also be set via environment variables.
The environment variable for a configuration option is the prefix TLSRPT_FETCHER_ followed by the configuration setting name in all caps.
For example the \-\-log_level option can instead by configured using the TLSRPT_FETCHER_LOG_LEVEL environment variable.
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure.
Data could not be delivered.
.RE
.SH "EXAMPLES"
.sp
Fetch list of domains that have reporting data for teh day of 2001\-02\-03.
Prints a transfer protocol header and a list of the domains with one domain per line.
The protocol header consists of two lines:
 \- the protocol version
 \- the current time of the data source in UTC
.sp
A single "." marks the end of the list:
.sp
\fBtlsrpt\-fetcher 2001\-02\-03\fP
.sp
Fetch report details for domain example.com for the day of 2001\-02\-03:
.sp
\fBtlsrpt\-fetcher 2001\-02\-03 example.com\fP
.SH "SEE ALSO"
.sp
\fBtlsrpt\-receiver\fP(1), \fBtlsrpt\-reporter\fP(1)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE