= tlsrpt-fetcher(1)
Boris Lohner
v0.5.0
:doctype: manpage
:manmanual: tlsrpt-fetcher
:mansource: tlsrpt-fetcher
:man-linkstyle: pass:[blue R < >]
:varpar-configsection: tlsrpt_fetcher
:varpar-environmentprefix: TLSRPT_FETCHER_

== Name

tlsrpt-fetcher - The data transfer agent to bring TLSRPT report data from the tlsrpt-collectd to the tlsrpt-reporter.

== Synopsis

*tlsrpt-fetcher* [_OPTION_] _DAY_ [_DOMAIN_]

== Description

The tlsrpt-fetcher is called by the tlsrpt-reporter to collect the pre-aggregated data from tlsrpt-collectds.
The data retrieval is done in two steps.

In the first step, the reporter asks for a list of domains for which data was collected.

In this step the reporter first checks if the tlsrpt-fetcher supports a matching protocol version in case future versions will use a different protocol.
The fetcher-protocol version is therefore the first line.

The second line is the current time of the tlsrpt-collectd/tlsrpt-fetcher bundle.
If the time differs too much from the time of the tlsrpt-reporter a warning is given that the data may not be completely processed.

The following lines are the domains, one domain per line.
The end of the list is signalled by a line containing just one single "."

== Options

*--storage*=_URL_::
  Use data storage described by _URL_.

include::manpage-common-options.adoc[]


== Exit status
*0*::
  Success.

*1*::
  Failure.
  Data could not be delivered.

== Examples

Fetch list of domains that have reporting data for teh day of 2001-02-03.
Prints a transfer protocol header and a list of the domains with one domain per line.
The protocol header consists of two lines:
 - the protocol version
 - the current time of the data source in UTC

A single "." marks the end of the list: 

*tlsrpt-fetcher 2001-02-03*


Fetch report details for domain example.com for the day of 2001-02-03:

*tlsrpt-fetcher 2001-02-03 example.com*

== See also
man:tlsrpt-collectd[1], man:tlsrpt-reporter[1]

include::manpage-copying.adoc[]
